Repository farm-service/backend, pull requests merged in 2024-04, with the labels that each got.

#11 ci: setup codium pr agent
  .github/workflows/pr-agent.yml
Labels: enhancement, Review effort [1-5]: 2

#13 !refactor(cd): BACKEND_ENVIRONMENT_VARIABLES parsing change
  .github/workflows/build-n-deploy.yml
Labels: enhancement, Review effort [1-5]: 2

#12 OrderItem and Status models have been created
  alembic.ini.example
  alembic/versions/2024_04_20_1308-4da0aac7c342_status_for_order.py
  alembic/versions/2024_04_20_1414-17060d1127ba_order_items.py
  app/admin/__init__.py
  app/admin/status.py
  app/models/__init__.py
  app/models/order_item.py
  app/models/status.py
Labels: enhancement, Review effort [1-5]: 3

#14 feat(cd): Docker run test implemented
  .github/workflows/docker-test.yml
  tests/reachability_test.sh
Labels: enhancement, Review effort [1-5]: 2, tests

#15 refactor(cd): reachability_test.sh removed as unused
  tests/reachability_test.sh
Labels: enhancement, Review effort [1-5]: 1

#17 cd: docker test now runs on RP syncs
  .github/workflows/docker-test.yml
Labels: enhancement, Review effort [1-5]: 1

#16 feature/generate order_items based on forecast
  .env.example
  .github/workflows/docker-test.yml
  alembic/versions/2024_04_22_1340-17af7f7b8bd1_order_items_have_status_id.py
  app/__init__.py
  app/admin/__init__.py
  app/admin/order_item.py
  app/configuration/server.py
  app/configuration/settings.py
  app/domain/__init__.py
  app/domain/calculate_orders.py
  app/domain/repositories/__init__.py
  app/domain/repositories/calculate_orders_repository_interface.py
  app/internal/events/__init__.py
  app/internal/events/calculate_orders_repository.py
  app/internal/events/generate_orders.py
  app/internal/integrations/__init__.py
  app/internal/integrations/get_forecast.py
  app/models/order_item.py
  app/models/product_ingredient_association.py
  app/serializers/ingredient.py
  app/serializers/product.py
  app/serializers/product_ingredient_association.py
  app/serializers/units_of_measurement.py
  requirements.txt
Labels: enhancement, Review effort [1-5]: 4
